ETH_NODE: ""
ETH_PRIVATE_KEY: ""
ARWEAVE_KEY_FILE: ""
ARWEAVE_NODE: ""
CONTRACT_ADDRESS: ""
TOKEN_ADDRESS: ""
FILE_PORT: ''
FEE_PER_BYTE: ''
MIN_BOUNTY: ''
MIN_DIGGING_FEE: ''
MAX_RESURRECTION_TIME: ''
ADD_TO_FREE_BOND: ''
REMOVE_FROM_FREE_BOND: ''